openapi: 3.2.0
info:
  title: Thenile Authentication API
  contact:
    email: support@thenile.dev
  version: '1.0'
  description: 'Operations tagged authentication across 4 of this provider''s published API definitions: api-openapi.json, global-openapi.json, thenile-database-openapi.yml, thenile-global-openapi.yml. Each path carries the servers of the definition it was published in.'
servers:
- url: https://global.thenile.dev
tags:
- name: Authentication
paths:
  /workspaces/{workspaceSlug}/databases/{databaseName}/tenants/auth/oidc/locations:
    get:
      tags:
      - Authentication
      summary: List SSO URLs
      description: Lists all SSO login URLs for all tenants in the database. The `provider` and `email` query parameters can be used to filter the results.
      operationId: globalListTenantSSOLocations
      parameters:
      - name: workspaceSlug
        in: path
        required: true
        schema:
          type: string
      - name: databaseName
        in: path
        required: true
        schema:
          type: string
      - name: provider
        in: query
        schema:
          type: string
      - name: email
        in: query
        schema:
          type: string
      responses:
        '200':
          description: List of authorization URLs
          content:
            application/json:
              schema:
                type: string
                format: uri
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
    servers:
    - url: https://global.thenile.dev
  /workspaces/{workspaceSlug}/databases/{databaseName}/tenants/auth/oidc/providers:
    get:
      tags:
      - Authentication
      summary: List registered SSO providers
      description: Lists all SSO providers registered for all tenants. The `provider` and `email` query parameters can be used to filter the results.
      operationId: globalListTenantSSOProviders
      parameters:
      - name: workspaceSlug
        in: path
        required: true
        schema:
          type: string
      - name: databaseName
        in: path
        required: true
        schema:
          type: string
      - name: provider
        in: query
        schema:
          type: string
      - name: email
        in: query
        schema:
          type: string
      responses:
        '200':
          description: List of registered providers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantSSORegistration'
      security:
      - jwtBearerAuth: []
    servers:
    - url: https://global.thenile.dev
  /workspaces/{workspaceSlug}/databases/{databaseName}/tenants/{tenantId}/auth/oidc/providers/{providerName}:
    get:
      tags:
      - Authentication
      summary: Get SSO registration
      description: Gets the configuration for a single sign-on provider registered for a tenant.
      operationId: globalGetTenantSSORegistration
      parameters:
      - name: workspaceSlug
        in: path
        required: true
        schema:
          type: string
      - name: databaseName
        in: path
        required: true
        schema:
          type: string
      - name: tenantId
        in: path
        required: true
        schema:
          type: string
      - name: providerName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The registered configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantSSORegistration'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      security:
      - jwtBearerAuth: []
    put:
      tags:
      - Authentication
      summary: Update tenant SSO provider
      description: Updates a single sign-on provider configuration for a specific tenant.
      operationId: globalUpdateTenantSSOProvider
      parameters:
      - name: workspaceSlug
        in: path
        required: true
        schema:
          type: string
      - name: databaseName
        in: path
        required: true
        schema:
          type: string
      - name: tenantId
        in: path
        required: true
        schema:
          type: string
      - name: providerName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Configuration details for a single sign-on provider. Any values provided will overwrite existing values. If a value is not provided, the existing value will be retained.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantSSORegistration'
            examples:
              Partial Configuration:
                description: Partial Configuration
                value: "{\n  \"clientId\": \"0oa1b2c3d4e5f6g7h8i9j\",\n  \"clientSecret\": \"a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2\",\n}\n"
      responses:
        '200':
          description: Updated configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantSSORegistration'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '404':
          description: Provider not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '502':
          description: Provider configuration does not match host URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      security:
      - jwtBearerAuth: []
    post:
      tags:
      - Authentication
      summary: Register tenant SSO provider
      description: Registers a single sign-on provider configuration for a specific tenant.
      operationId: globalRegisterTenantSSOProvider
      parameters:
      - name: workspaceSlug
        in: path
        required: true
        schema:
          type: string
      - name: databaseName
        in: path
        required: true
        schema:
          type: string
      - name: tenantId
        in: path
        required: true
        schema:
          type: string
      - name: providerName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: 'Configuration details for a single sign-on provider, including the email domains that should be associated with the provider.

          Note: the email domains you provide should usually correspond to the domains configured with the provider.'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantSSORegistration'
            examples:
              Sample Okta Configuration:
                description: Sample Okta Configuration
                value:
                  configUrl: https://dev-123456.okta.com/.well-known/openid-configuration
                  clientId: 0oa1b2c3d4e5f6g7h8i9j
                  clientSecret: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2
                  emailDomains:
                  - mycompany.com
                  - anothercompany.com
                  enabled: true
      responses:
        '200':
          description: Registered configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantSSORegistration'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '409':
          description: Provider already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '502':
          description: Provider configuration does not match host URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      security:
      - jwtBearerAuth: []
    servers:
    - url: https://global.thenile.dev
  /workspaces/{workspaceSlug}/databases/{databaseName}/tenants/{tenantId}/auth/oidc/providers:
    get:
      tags:
      - Authentication
      summary: List SSO registrations
      description: Lists all single sign-on provider configurations that are registered for a tenant.
      operationId: globalListTenantSSORegistrations
      parameters:
      - name: workspaceSlug
        in: path
        required: true
        schema:
          type: string
      - name: databaseName
        in: path
        required: true
        schema:
          type: string
      - name: tenantId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: List of registered configurations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TenantSSORegistration'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      security:
      - jwtBearerAuth: []
    servers:
    - url: https://global.thenile.dev
  /workspaces/{workspaceSlug}/databases/{databaseName}/tenants/{tenantId}/auth/oidc/providers/{providerName}/login:
    get:
      tags:
      - Authentication
      summary: Initiate OIDC login for a tenant
      description: Initiates the OIDC login flow for a registered authentication provider.
      operationId: globalLoginTenantProvider
      parameters:
      - name: workspaceSlug
        in: path
        required: true
        schema:
          type: string
      - name: databaseName
        in: path
        required: true
        schema:
          type: string
      - name: tenantId
        in: path
        required: true
        schema:
          type: string
      - name: providerName
        in: path
        required: true
        schema:
          type: string
      responses:
        '302':
          description: Redirect to the provider's login page
        '404':
          description: Unknown OIDC provider
    servers:
    - url: https://global.thenile.dev
  /databases/{databaseId}/auth/oidc/providers:
    get:
      tags:
      - Authentication
      summary: List OIDC providers
      description: Lists all OIDC providers registered in the database.
      operationId: listOIDCProviders
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: List of OIDC providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OIDCProvider'
    post:
      tags:
      - Authentication
      summary: Create OIDC provider
      description: 'Creates an OIDC provider with the database. During creation, the well-known configuration is loaded from the `configUrl` and stored in the database.

        Google and Okta are supported out of the box. Use this endpoint to register other OIDC providers.'
      operationId: createOIDCProvider
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: The configuration for a new OIDC provider. A provider must have a unique name and a valid `configUrl` pointing to the well-known OIDC configuration. If the provider is enabled, the `redirectUrl` back to your application must be specified. (Without the `redirectUrl`, Nile cannot resolve authentication attempts.)
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OIDCProvider'
            examples:
              Create Social Provider:
                summary: Registers a new social login provider
                description: Create Social Provider
                value:
                  name: Some Social Host
                  authType: SOCIAL
                  enabled: true
                  configUrl: https://some-social-host.com/.well-known/openid-configuration
                  redirectUrl: https://myapp.com/auth/handler
              Create SSO Provider:
                summary: Registers a new SSO provider
                description: Create SSO Provider
                value:
                  name: Some SSO Host
                  authType: SSO
                  enabled: true
                  configUrl: https://some-sso-host.com/.well-known/openid-configuration
                  redirectUrl: https://myapp.com/auth/handler
      responses:
        '200':
          description: Updated OIDC provider
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OIDCProvider'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '409':
          description: OIDC provider already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '502':
          description: OIDC provider configuration does not match host URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      security:
      - jwtBearerAuth: []
    servers:
    - url: https://global.thenile.dev
  /databases/{databaseId}/auth/oidc/providers/{providerName}:
    get:
      tags:
      - Authentication
      summary: Get an OIDC provider
      description: Gets an OIDC provider by name. If the well-known config for the provider is determined to have expired, the latest config is fetched and retained, ensuring that the provider information returned is always current.
      operationId: getOIDCProvider
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      - name: providerName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OIDC provider
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OIDCProvider'
        '404':
          description: OIDC provider not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
    put:
      tags:
      - Authentication
      summary: Update OIDC provider
      description: Updates a named OIDC provider. During an update, the well-known configuration is refreshed.
      operationId: updateOIDCProvider
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      - name: providerName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: The new configuration values for an existing OIDC provider. (The `name` may not be modified.) If the provider is enabled, the `redirectUrl` back to your application must be specified. (Without the `redirectUrl`, Nile cannot resolve authentication attempts.)
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OIDCProvider'
            examples:
              Update Social Provider:
                summary: Updates the existing social provider configuration
                description: Update Social Provider
                value:
                  name: Some Social Host
                  authType: SOCIAL
                  enabled: true
                  configUrl: https://some-social-host.com/.well-known/openid-configuration
                  redirectUrl: https://myapp.com/auth/handler
              Update SSO Provider:
                summary: Updates the existing SSO provider configuration
                description: Update SSO Provider
                value:
                  name: Some SSO Host
                  authType: SSO
                  enabled: true
                  configUrl: https://some-sso-host.com/.well-known/openid-configuration
                  redirectUrl: https://myapp.com/auth/handler
      responses:
        '200':
          description: Updated OIDC provider
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OIDCProvider'
        '400':
          description: OIDC provider name mismatch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '404':
          description: OIDC provider not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      security:
      - jwtBearerAuth: []
    servers:
    - url: https://global.thenile.dev
  /databases/{databaseId}/auth/oidc/relyingparties:
    get:
      tags:
      - Authentication
      summary: List relying parties
      description: Lists all OIDC relying parties in the database.
      operationId: listRelyingParties
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: List of relying parties
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OIDCRelyingParty'
      security:
      - jwtBearerAuth: []
    put:
      tags:
      - Authentication
      summary: Update relying party
      description: Updates an OIDC relying party. The `clientId`, `clientSecret` and `enabled` properties may be modified.
      operationId: updateRelyingParty
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Configuration details for an existing OIDC relying party. The `clientId`, `clientSecret` and `enabled` properties may be modified.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OIDCRelyingParty'
            examples:
              Create Relying Party Request:
                summary: Registers a relying party for an OIDC provider
                description: Create Relying Party Request
                value:
                  provider: GOOGLE
                  clientId: 0oa1b2c3d4e5f6g7h8i9j
                  clientSecret: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2
                  enabled: true
      responses:
        '200':
          description: Relying party updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OIDCRelyingParty'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '404':
          description: Relying party not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      security:
      - jwtBearerAuth: []
    post:
      tags:
      - Authentication
      summary: Create relying party
      description: Creates a relying party associated with a known OIDC provider.
      operationId: createRelyingParty
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Configuration details for an OIDC relying party that relies on  a registered OIDC provider. This should include the client ID and secret for the relying party.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OIDCRelyingParty'
            examples:
              Create Relying Party Request:
                summary: Registers a relying party for an OIDC provider
                description: Create Relying Party Request
                value:
                  provider: GOOGLE
                  clientId: 0oa1b2c3d4e5f6g7h8i9j
                  clientSecret: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2
                  enabled: true
      responses:
        '201':
          description: Relying party created successfully
      security:
      - jwtBearerAuth: []
    servers:
    - url: https://global.thenile.dev
  /databases/{databaseId}/auth/oidc/relyingparties/{relyingPartyId}:
    get:
      tags:
      - Authentication
      summary: Get a relying party
      description: Get an OIDC relying party by its identifier.
      operationId: getRelyingParty
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      - name: relyingPartyId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The relying party
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OIDCRelyingParty'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '404':
          description: Relying party not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      security:
      - jwtBearerAuth: []
    servers:
    - url: https://global.thenile.dev
  /databases/{databaseId}/tenants/auth/oidc/locations:
    get:
      tags:
      - Authentication
      summary: List SSO URLs
      description: Lists all SSO login URLs for all tenants in the database. The `provider` and `email` query parameters can be used to filter the results.
      operationId: listTenantSSOLocations
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      - name: provider
        in: query
        schema:
          type: string
      - name: email
        in: query
        schema:
          type: string
      responses:
        '200':
          description: List of authorization URLs
          content:
            application/json:
              schema:
                type: string
                format: uri
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
    servers:
    - url: https://global.thenile.dev
  /databases/{databaseId}/tenants/auth/oidc/providers:
    get:
      tags:
      - Authentication
      summary: List registered SSO providers
      description: Lists all SSO providers registered for all tenants. The `provider` and `email` query parameters can be used to filter the results.
      operationId: listTenantSSOProviders
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      - name: provider
        in: query
        schema:
          type: string
      - name: email
        in: query
        schema:
          type: string
      responses:
        '200':
          description: List of registered providers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantSSORegistration'
      security:
      - jwtBearerAuth: []
    servers:
    - url: https://global.thenile.dev
  /databases/{databaseId}/tenants/{tenantId}/auth/oidc/providers/{providerName}:
    get:
      tags:
      - Authentication
      summary: Get SSO registration
      description: Gets the configuration for a single sign-on provider registered for a tenant.
      operationId: getTenantSSORegistration
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      - name: tenantId
        in: path
        required: true
        schema:
          type: string
      - name: providerName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The registered configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantSSORegistration'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      security:
      - jwtBearerAuth: []
    put:
      tags:
      - Authentication
      summary: Update tenant SSO provider
      description: Updates a single sign-on provider configuration for a specific tenant.
      operationId: updateTenantSSOProvider
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      - name: tenantId
        in: path
        required: true
        schema:
          type: string
      - name: providerName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Configuration details for a single sign-on provider. Any values provided will overwrite existing values. If a value is not provided, the existing value will be retained.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantSSORegistration'
            examples:
              Partial Configuration:
                description: Partial Configuration
                value: "{\n  \"clientId\": \"0oa1b2c3d4e5f6g7h8i9j\",\n  \"clientSecret\": \"a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2\",\n}\n"
      responses:
        '200':
          description: Updated configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantSSORegistration'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '404':
          description: Provider not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '502':
          description: Provider configuration does not match host URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      security:
      - jwtBearerAuth: []
    post:
      tags:
      - Authentication
      summary: Register tenant SSO provider
      description: Registers a single sign-on provider configuration for a specific tenant.
      operationId: registerTenantSSOProvider
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      - name: tenantId
        in: path
        required: true
        schema:
          type: string
      - name: providerName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: 'Configuration details for a single sign-on provider, including the email domains that should be associated with the provider.

          Note: the email domains you provide should usually correspond to the domains configured with the provider.'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantSSORegistration'
            examples:
              Sample Okta Configuration:
                description: Sample Okta Configuration
                value:
                  configUrl: https://dev-123456.okta.com/.well-known/openid-configuration
                  clientId: 0oa1b2c3d4e5f6g7h8i9j
                  clientSecret: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2
                  emailDomains:
                  - mycompany.com
                  - anothercompany.com
                  enabled: true
      responses:
        '200':
          description: Registered configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantSSORegistration'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '409':
          description: Provider already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '502':
          description: Provider configuration does not match host URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      security:
      - jwtBearerAuth: []
    servers:
    - url: https://global.thenile.dev
  /databases/{databaseId}/tenants/{tenantId}/auth/oidc/providers:
    get:
      tags:
      - Authentication
      summary: List SSO registrations
      description: Lists all single sign-on provider configurations that are registered for a tenant.
      operationId: listTenantSSORegistrations
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      - name: tenantId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: List of registered configurations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TenantSSORegistration'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
      security:
      - jwtBearerAuth: []
    servers:
    - url: https://global.thenile.dev
  /databases/{databaseId}/tenants/{tenantId}/auth/oidc/providers/{providerName}/login:
    get:
      tags:
      - Authentication
      summary: Initiate OIDC login for a tenant
      description: Initiates the OIDC login flow for a registered authentication provider.
      operationId: loginTenantProvider
      parameters:
      - name: databaseId
        in: path
        required: true
        schema:
          type: string
      - name: tenantId
        in: path
        required: true
        schema:
          type: string
      - name: providerName
        in: path
        required: true
        schema:
          type: string
      responses:
        '302':
          description: Redirect to the provider's login page
        '404':
          description: Unknown OIDC provider
    servers:
    - url: https://global.thenile.dev
  /workspaces/{workspaceSlug}/databases/{databaseName}/credentials:
    get:
      tags:
      - Authentication
      summary: Lists credentials for a database
      description: 'Lists all credentials that exist for a database. The id of the credential is

        included in the response, but not the password. Passwords are provided only once,

        at the time the credential is created, and are encrypted for storage.'
      operationId: listCredentials
      parameters:
      - name: workspaceSlug
        in: path
        required: true
        schema:
          type: string
      - name: databaseName
        in: path
        required: true
        schema:
          type: string
      - name: tenantId
        in: query
        schema:
          type: string
      - name: internal
        in: query
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: A list of Credential objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetCredentialResponse'
        '401':
          description: Unauthorized. Credentials were missing or expired.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError_2'
        '403':
          description: Forbidden. The credentials provided do not grant access to the requested resource(s).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError_2'
      security:
      - jwtBearerAuth: []
    post:
      tags:
      - Authentication
      summary: Create a database credential
      description: 'Generates a new secure credential for a database. The generated password is

        returned in the response, and is the only time the password is available in

        plaintext. No request body is required."'
      operationId: createCredential
      parameters:
      - name: workspaceSlug
        in: path
        required: true
        schema:
          type: string
      - name: databaseName
        in: path
        required: true
        schema:
          type: string
      - name: tenantId
        in: query
        schema:
          type: string
      - name: internal
        in: query
        schema:
          type: boolean
          default: false
      responses:
        '200':
          description: Credential created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCredentialResponse'
        '401':
          description: Unauthorized. Credentials were missing or expired.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError_2'
        '403':
          description: Forbidden. The credentials provided do not grant access to the requested resource(s).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError_2'
      security:
      - jwtBearerAuth: []
    servers:
    - url: https://global.thenile.dev
  /workspaces/{workspaceSlug}/databases/{databaseName}/credentials/{credentialId}:
    delete:
      tags:
      - Authentication
      summary: Delete a database credential
      description: Deletes an existing database credential. No request body is required."
      operationId: deleteCredential
      parameters:
      - name: workspaceSlug
        in: path
        required: true
        schema:
          type: string
      - name: databaseName
        in: path
        required: true
        schema:
          type: string
      - name: credentialId
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Credential deleted
        '401':
          description: Unauthorized. Credentials were missing or expired.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError_2'
        '403':
          description: Forbidden. The credentials provided do not grant access to the requested resource(s).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError_2'
      security:
      - jwtBearerAuth: []
    servers:
    - url: https://global.thenile.dev
  /workspaces/{workspaceSlug}/databases/{databaseName}/credentials/rotate:
    post:
      tags:
      - Authentication
      summary: Rotate a database credential
      description: Generates a new credential and schedules existing credentials for deletion after the provided delay.
      operationId: rotateCredential
      parameters:
      - name: workspaceSlug
        in: path
        required: true
        schema:
          type: string
      - name: databaseName
        in: path
        required: true
        schema:
          type: string
      - name: tenantId
        in: query
        schema:
          type: string
      - name: internal
        in: query
        schema:
          type: boolean
          default: false
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/RotateCredentialRequest'
      responses:
        '200':
          description: New credential after rotation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCredentialResponse'
      security:
      - jwtBearerAuth: []
    servers:
    - url: https://global.thenile.dev
  /oauth2/token:
    post:
      tags:
      - Authentication
      summary: Exchange an authorization code or refresh token
      description: Uses OAuth client credentials or a PKCE verifier to exchange an authorization code, or refreshes an existing access token.
      operationId: getToken
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                code:
                  type: string
                code_verifier:
                  type: string
                redirect_uri:
                  type: string
                client_id:
                  type: string
                client_secret:
                  type: string
                refresh_token:
                  type: string
                scope:
                  type: string
      responses:
        '200':
          description: OAuth access and refresh tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
    servers:
    - url: https://global.thenile.dev
components:
  schemas:
    OIDCRelyingParty:
      required:
      - clientId
      - clientSecret
      - provider
      type: object
      properties:
        id:
          type: string
        tenantId:
          type: string
        provider:
          type: string
        clientId:
          minLength: 1
          type: string
        clientSecret:
          minLength: 1
          type: string
        emailDomains:
          type: array
          items:
            type: string
        enabled:
          type: boolean
    APIError:
      required:
      - errorCode
      - message
      - statusCode
      type: object
      properties:
        errorCode:
          type: string
          enum:
          - internal_error
          - bad_request
          - unsupported_operation
          - entity_not_found
          - duplicate_entity
          - invalid_credentials
          - unknown_oidc_provider
          - unknown_oidc_party
          - provider_already_exists
          - provider_config_error
          - provider_mismatch
          - provider_update_error
          - provider_disabled
          - session_state_missing
          - session_state_mismatch
          - oidc_code_missing
          - tenant_not_found
          - constraint_violation
          - sql_exception
          - db_creation_failure
          - db_status_failure
          - db_initialization_failure
          - db_config_missing
          - unauthorized_workspace_access
          - email_send_failure
          - jdbc_exception
          - oidc_exception
          - region_mismatch
          - credential_creation_failure
          - credential_propagation_failure
          - pdb_creation_failure
          - get_pdbs_failure
          - get_ldbs_placed_on_pdb_failure
          - credential_deletion_failure
          - get_ldb_on_pdb_placement_status_failure
          - pdb_deletion_failure
          - missing_flavor_id
        message:
          minLength: 1
          type: string
        statusCode:
          type: integer
          format: int32
    OIDCProvider:
      required:
      - authType
      - name
      type: object
      properties:
        name:
          minLength: 1
          type: string
        authType:
          type: string
          enum:
          - SSO
          - SOCIAL
        redirectUrl:
          type: string
          format: uri
        enabled:
          type: boolean
        configUrl:
          type: string
          format: uri
        config:
          $ref: '#/components/schemas/JsonNode'
        ttl_sec:
          type: integer
          format: int32
    TenantSSORegistration:
      required:
      - clientId
      - configUrl
      - provider
      - tenantId
      type: object
      properties:
        id:
          type: string
          readOnly: true
        tenantId:
          type: string
        provider:
          type: string
        configUrl:
          type: string
          format: uri
        clientId:
          minLength: 1
          type: string
        emailDomains:
          type: array
          items:
            type: string
        enabled:
          type: boolean
    JsonNode:
      type: object
    TokenResponse:
      type: object
      properties:
        token_type:
          type: string
        access_token:
          type: string
        refresh_token:
          type: string
        expires_in:
          type: integer
          format: int64
    DatabaseParentResponse:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
        name:
          minLength: 1
          type: string
    Workspace:
      required:
      - name
      - slug
      type: object
      properties:
        id:
          type: string
        name:
          minLength: 1
          type: string
        slug:
          minLength: 1
          type: string
        stripe_customer_id:
          type: string
        created:
          type: string
          format: date-time
    GetDatabaseResponse:
      required:
      - expandable
      - id
      - name
      - region
      - status
      - workspace
      type: object
      properties:
        id:
          type: string
        name:
          minLength: 1
          type: string
        workspace:
          $ref: '#/components/schemas/Workspace'
        status:
          type: string
          enum:
          - PENDING
          - REQUESTED
          - BUILT
          - POOLED
          - READY
        region:
          type: string
          enum:
          - AWS_US_WEST_2
          - AWS_US_EAST_1
          - AWS_EU_CENTRAL_1
          - AZURE_EASTUS
        expandable:
          type: boolean
        created:
          type: string
          format: date-time
        deleted:
          type: string
          format: date-time
        apiHost:
          type:
          - string
          - 'null'
          description: Public database API URL; Since it is only used for tenants/users management, it is null for un-sharded databases.
          format: uri
        dbHost:
          type: string
          format: uri
        parent:
          $ref: '#/components/schemas/DatabaseParentResponse'
    APIError_2:
      required:
      - errorCode
      - message
      - statusCode
      type: object
      properties:
        errorCode:
          type: string
          enum:
          - internal_error
          - bad_request
          - unsupported_operation
          - forbidden_operation
          - entity_not_found
          - duplicate_entity
          - invalid_credentials
          - unknown_oidc_provider
          - unknown_oidc_party
          - provider_already_exists
          - provider_config_error
          - provider_mismatch
          - provider_update_error
          - provider_disabled
          - session_state_missing
          - session_state_mismatch
          - oidc_code_missing
          - tenant_not_found
          - constraint_violation
          - sql_exception
          - db_creation_failure
          - db_rename_failure
          - db_status_failure
          - db_initialization_failure
          - db_deletion_failure
          - db_config_missing
          - unauthorized_workspace_access
          - email_send_failure
          - jdbc_exception
          - oidc_exception
          - region_mismatch
          - credential_creation_failure
          - credential_propagation_failure
          - unauthorized_client
          - unsupported_response_type
          - invalid_request
          - server_error
          - access_denied
          - feature_ineligible
          - customer_lookup_failure
          - threshold_exceeded
          - create_rejected
        message:
          minLength: 1
          type: string
        statusCode:
          type: integer
          format: int32
    GetCredentialResponse:
      required:
      - database
      - id
      type: object
      properties:
        id:
          minLength: 1
          type: string
        database:
          $ref: '#/components/schemas/GetDatabaseResponse'
        tenant:
          type: string
        internal:
          type: boolean
        created:
          type: string
          format: date-time
    RotateCredentialRequest:
      type: object
      properties:
        delayOldSecretsExpirationHours:
          maximum: 720
          minimum: 0
          type: number
          format: double
        reason:
          type: string
    CreateCredentialResponse:
      required:
      - database
      - id
      - password
      type: object
      properties:
        id:
          minLength: 1
          type: string
        database:
          $ref: '#/components/schemas/GetDatabaseResponse'
        tenant:
          type: string
        internal:
          type: boolean
        password:
          minLength: 1
          type: string
        created:
          type: string
          format: date-time
    APIError_3:
      required:
      - errorCode
      - message
      - statusCode
      type: object
      properties:
        errorCode:
          type: string
          enum:
          - internal_error
          - bad_request
          - unsupported_operation
          - forbidden_operation
          - entity_not_found
          - duplicate_entity
          - invalid_credentials
          - unknown_oidc_provider
          - unknown_oidc_party
          - provider_already_exists
          - provider_config_error
          - provider_mismatch
          - provider_update_error
          - provider_disabled
          - session_state_missing
          - session_state_mismatch
          - oidc_code_missing
          - tenant_not_found
          - constraint_violation
          - sql_exception
          - db_creation_failure
          - db_rename_failure
          - db_status_failure
          - db_initialization_failure
          - db_deletion_failure
          - db_config_missing
          - unauthorized_workspace_access
          - email_send_failure
          - jdbc_exception
          - oidc_exception
          - region_mismatch
          - credential_creation_failure
          - credential_propagation_failure
          - unauthorized_client
          - unsupported_response_type
          - invalid_request
          - server_error
          - access_denied
          - feature_ineligible
          - customer_lookup_failure
          - threshold_exceeded
          - create_rejected
        message:
          minLength: 1
          type: string
        statusCode:
          type: integer
          format: int32
  securitySchemes:
    jwtBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-refined-from:
- api-openapi.json
- global-openapi.json
- thenile-database-openapi.yml
- thenile-global-openapi.yml
